### ISSUE TITLE
Player externe

### ISSUE THREAD

**Issue by pierrelegall** [Zenika/zenikast#28]
Si l'on partage le lien sur une plateforme tel que Twitter ou encore Slack, un player externe doit s'afficher pour permettre d'écouter un podcast directement depuis cette plateforme.

À faire :
- étudier ce fonctionnement
- proposer une solution

**Comment by lepieru** [comment]
We should respect this specification : https://oembed.com/#section7

**Comment by lepieru** [comment]
See branch `experiment/28-external-player` which should not be merge.

https://github.com/Zenika/zenikast/tree/experiment/28-external-player
