### ISSUE TITLE
Ajouter description de l'intérêt de le logger

### ISSUE THREAD

**Issue by pierrelegall** [Zenika/zenikast#38]
Rien n'indique dans l'application l'intérêt de se connecter à l'application.

Réfléchir à comment informer l'utilisateur de l'intérêt de se logger et réaliser les modifications.

**Comment by lepieru** [comment]
Est-ce qu'une note d'information sur la page de login fait l'affaire ? Ou vous voyez ça autrement (ex. pop-up relou sur la main page) ?

Poke @kefranabg.
